import type { SportConfig } from '../../types'

// Reuses NFL's stat-key vocabulary (passingYards, defInterceptions, etc.) —
// college football box scores map onto the same categories, so there's no
// need to invent a parallel schema.
export const cfbConfig: SportConfig = {
  id: 'cfb',
  label: 'College Football',
  engine: 'headToHead',
  season: {
    startDate: '2026-08-29',
    periodLabel: 'Week',
    totalPeriods: 14,
  },
  realSeasonWindow: { start: '2026-08-29', end: '2027-01-20' },
  positions: ['QB', 'RB', 'WR', 'TE', 'K', 'DST'],
  roster: [
    { slot: 'QB', eligiblePositions: ['QB'], count: 1 },
    { slot: 'RB', eligiblePositions: ['RB'], count: 2 },
    { slot: 'WR', eligiblePositions: ['WR'], count: 2 },
    { slot: 'TE', eligiblePositions: ['TE'], count: 1 },
    { slot: 'FLEX', eligiblePositions: ['RB', 'WR', 'TE'], count: 1 },
    { slot: 'DST', eligiblePositions: ['DST'], count: 1 },
    { slot: 'K', eligiblePositions: ['K'], count: 1 },
    {
      slot: 'BN',
      eligiblePositions: ['QB', 'RB', 'WR', 'TE', 'K', 'DST'],
      count: 6,
      isBench: true,
    },
  ],
  scoringPresets: {
    standard: {
      id: 'standard',
      label: 'Standard',
      weights: {
        passingYards: 0.04,
        passingTDs: 4,
        interceptionsThrown: -2,
        rushingYards: 0.1,
        rushingTDs: 6,
        receptions: 0,
        receivingYards: 0.1,
        receivingTDs: 6,
        fumblesLost: -2,
        fieldGoalsMade: 3,
        extraPointsMade: 1,
        sacks: 1,
        defInterceptions: 2,
        fumbleRecoveries: 2,
        defensiveTDs: 6,
        safeties: 2,
        pointsAllowed: -0.1,
      },
    },
    ppr: {
      id: 'ppr',
      label: 'PPR',
      weights: {
        passingYards: 0.04,
        passingTDs: 4,
        interceptionsThrown: -2,
        rushingYards: 0.1,
        rushingTDs: 6,
        receptions: 1,
        receivingYards: 0.1,
        receivingTDs: 6,
        fumblesLost: -2,
        fieldGoalsMade: 3,
        extraPointsMade: 1,
        sacks: 1,
        defInterceptions: 2,
        fumbleRecoveries: 2,
        defensiveTDs: 6,
        safeties: 2,
        pointsAllowed: -0.1,
      },
    },
    custom: {
      id: 'custom',
      label: 'Custom',
      weights: {
        passingYards: 0.04,
        passingTDs: 4,
        interceptionsThrown: -2,
        rushingYards: 0.1,
        rushingTDs: 6,
        receptions: 0.5,
        receivingYards: 0.1,
        receivingTDs: 6,
        fumblesLost: -2,
        fieldGoalsMade: 3,
        extraPointsMade: 1,
        sacks: 1,
        defInterceptions: 2,
        fumbleRecoveries: 2,
        defensiveTDs: 6,
        safeties: 2,
        pointsAllowed: -0.1,
      },
    },
  },
  draft: { type: 'snake', rounds: 15, pickTimeSeconds: 60 },
  lineupLock: 'perPlayerGameTime',
  // 12 regular-season weeks, then a 4-team single-elimination bracket over
  // the final 2 weeks (semifinal, championship) — mirrors the College
  // Football Playoff structure at a manageable scale for an 8-team league.
  playoffs: { teamCount: 4, weeks: 2 },
}
